import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import localFont from 'next/font/local'
import Navbar from './Components/Navbar'
import Footer from './Components/Footer'
import SubNav from './Components/SubNav'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
	return (
	<html lang="en">
		<body className="relative uppercase bg-[#FBF1EA] ">
			<Navbar />
			{children}
			<SubNav/>
			<Footer/>
		</body>
	</html>
	)
}
